/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

import banco.model.Usuario;
import java.awt.event.ActionEvent;

/**
 *
 * @author keslleyjr
 */
public class TelaMenuPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaMenuPrincipal.class.getName());

    private Usuario usuarioLogado;

    /**
     * Creates new form TelaMenuPrincipal
     */
    public TelaMenuPrincipal(Usuario usuario) {
        this.usuarioLogado = usuario;
        initComponents();
        setSize(900, 700);
        setLocationRelativeTo(null);
        lSaud.setText("Bem-Vindo(a), " + (usuario != null ? usuario.getNome() : ""));
        
        if (usuario != null && !"ADMIN".equals(usuario.getPerfil())) {
            menuGer.setVisible(false);
        }

        // Action Listeners
        menuGer.addActionListener(this::abrirTelaGerenciarUsuarios);
        menuCadCliente.addActionListener(this::abrirTelaCadastroCliente);
        menuCadCorrente.addActionListener(this::abrirTelaCadastroContaCorrente);
        menuCadPoupanca.addActionListener(this::abrirTelaCadastroContaPoupanca);
        menuRel.addActionListener(this::abrirTelaRelatorio);
        
        menuOp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                abrirTelaOperacoes(null);
            }
        });
    }
    
    public TelaMenuPrincipal() {
        this(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lSaud = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSair = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu = new javax.swing.JMenu();
        menuGer = new javax.swing.JMenuItem();
        menuExt = new javax.swing.JMenuItem();
        menuRel = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuCadCliente = new javax.swing.JMenuItem();
        menuCadCorrente = new javax.swing.JMenuItem();
        menuCadPoupanca = new javax.swing.JMenuItem();
        menuOp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lSaud.setText("Bem-Vindo(a), [nome do usuário]");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(lSaud)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lSaud)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        btnSair.setText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(this::btnSairActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 58, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        JMenu.setText("Gerenciar");
        JMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuGer.setText("Gerenciar Usuários");
        menuGer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JMenu.add(menuGer);

        menuExt.setText("Extrato da Conta");
        menuExt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menuExt.addActionListener(this::menuExtActionPerformed);
        JMenu.add(menuExt);

        menuRel.setText("Relatório Geral do Banco");
        menuRel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JMenu.add(menuRel);

        jMenuBar1.add(JMenu);

        jMenu2.setText("Cadastro");
        jMenu2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        menuCadCliente.setText("Cadastrar Cliente");
        menuCadCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(menuCadCliente);

        menuCadCorrente.setText("Cadastrar Conta Corrente");
        menuCadCorrente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(menuCadCorrente);

        menuCadPoupanca.setText("Cadastrar Conta Poupança");
        menuCadPoupanca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenu2.add(menuCadPoupanca);

        jMenuBar1.add(jMenu2);

        menuOp.setText("Operações");
        menuOp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuBar1.add(menuOp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new TelaLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void menuExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExtActionPerformed
        new TelaExtrato().setVisible(true);
    }//GEN-LAST:event_menuExtActionPerformed

    private void abrirTelaGerenciarUsuarios(ActionEvent evt) {
        new TelaGerenciarUsuarios().setVisible(true);
    }

    private void abrirTelaCadastroCliente(ActionEvent evt) {
        new TelaCadastroCliente().setVisible(true);
    }

    private void abrirTelaCadastroContaCorrente(ActionEvent evt) {
        new TelaCadastroContaCorrente().setVisible(true);
    }

    private void abrirTelaCadastroContaPoupanca(ActionEvent evt) {
        new TelaCadastroContaPoupanca().setVisible(true);
    }

    private void abrirTelaRelatorio(ActionEvent evt) {
        new TelaRelatorio().setVisible(true);
    }

    private void abrirTelaOperacoes(ActionEvent evt) {
        new TelaOperacoes().setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaMenuPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JMenu;
    private javax.swing.JButton btnSair;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lSaud;
    private javax.swing.JMenuItem menuCadCliente;
    private javax.swing.JMenuItem menuCadCorrente;
    private javax.swing.JMenuItem menuCadPoupanca;
    private javax.swing.JMenuItem menuExt;
    private javax.swing.JMenuItem menuGer;
    private javax.swing.JMenu menuOp;
    private javax.swing.JMenuItem menuRel;
    // End of variables declaration//GEN-END:variables
}
