/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

import banco.model.ContaBancaria;
import banco.model.ContaCorrente;
import banco.model.ContaPoupanca;
import banco.service.BancoService;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Component;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JTable;

/**
 *
 * @author keslleyjr
 */
public class TelaRelatorio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaRelatorio.class.getName());

    private final BancoService bancoService = new BancoService();
    private Double maiorSaldo = null;
    private Double menorSaldo = null;

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();
        configurarRendererTabela();
        carregarRelatorio();
        btnAtualizar.addActionListener(e -> carregarRelatorio());
    }
    
    private void configurarRendererTabela() {
        tListaConta.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, 
                    boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                
                if (!isSelected) {
                    // Pega o saldo da linha a partir do modelo
                    // Na nossa tabela, a coluna 3 é o Saldo
                    String saldoStr = (String) table.getModel().getValueAt(row, 3);
                    double saldo = Double.parseDouble(saldoStr.replace("R$ ", "").replace(",", "."));
                    
                    if (maiorSaldo != null && menorSaldo != null && maiorSaldo > menorSaldo) {
                        if (saldo == maiorSaldo) {
                            c.setBackground(new Color(144, 238, 144)); // Verde claro
                            c.setFont(c.getFont().deriveFont(Font.BOLD));
                        } else if (saldo == menorSaldo) {
                            c.setBackground(new Color(255, 182, 193)); // Vermelho claro
                            c.setFont(c.getFont().deriveFont(Font.BOLD));
                        } else {
                            c.setBackground(Color.WHITE);
                            c.setFont(c.getFont().deriveFont(Font.PLAIN));
                        }
                    } else {
                        c.setBackground(Color.WHITE);
                        c.setFont(c.getFont().deriveFont(Font.PLAIN));
                    }
                }
                return c;
            }
        });
    }

    private void carregarRelatorio() {
        List<ContaBancaria> contas = bancoService.listarTodasContas();
        
        int totalCorrente = 0;
        int totalPoupanca = 0;
        double patrimonio = 0.0;
        maiorSaldo = null;
        menorSaldo = null;
        
        DefaultTableModel model = (DefaultTableModel) tListaConta.getModel();
        model.setRowCount(0);
        
        for (ContaBancaria c : contas) {
            if (c instanceof ContaCorrente) totalCorrente++;
            if (c instanceof ContaPoupanca) totalPoupanca++;
            
            double saldo = c.getSaldo();
            patrimonio += saldo;
            
            if (maiorSaldo == null || saldo > maiorSaldo) maiorSaldo = saldo;
            if (menorSaldo == null || saldo < menorSaldo) menorSaldo = saldo;
            
            model.addRow(new Object[]{
                c.getNumeroConta(),
                c.getTitular().getNome(),
                c instanceof ContaCorrente ? "Corrente" : "Poupança",
                String.format("R$ %.2f", saldo)
            });
        }
        
        lCorrentesQuant.setText(String.valueOf(totalCorrente));
        lPoupancasQuant.setText(String.valueOf(totalPoupanca));
        lTotalBanco.setText(String.format("R$ %.2f", patrimonio));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lCorrentesQuant = new javax.swing.JLabel();
        lPoupancasQuant = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lTotalBanco = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tListaConta = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Total de Contas Correntes:");

        jLabel2.setText("Total de Contas Poupanças:");

        lCorrentesQuant.setText("jLabel3");

        lPoupancasQuant.setText("jLabel4");

        jLabel5.setText("Patrimônio total do banco:");

        lTotalBanco.setText("jLabel6");

        tListaConta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Titular", "Tipo", "Saldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tListaConta);

        btnAtualizar.setText("Atualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel5)
                        .addGap(42, 42, 42)
                        .addComponent(lTotalBanco))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btnAtualizar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lPoupancasQuant)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lCorrentesQuant)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lCorrentesQuant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lPoupancasQuant))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lTotalBanco))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaRelatorio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCorrentesQuant;
    private javax.swing.JLabel lPoupancasQuant;
    private javax.swing.JLabel lTotalBanco;
    private javax.swing.JTable tListaConta;
    // End of variables declaration//GEN-END:variables
}
