/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

import banco.model.ContaBancaria;
import banco.model.ContaCorrente;
import banco.model.ContaPoupanca;
import banco.model.Transacao;
import banco.service.BancoService;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author keslleyjr
 */
public class TelaExtrato extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaExtrato.class.getName());

    private final BancoService bancoService = new BancoService();
    private ContaBancaria contaAtual;

    /**
     * Creates new form TelaExtrato
     */
    public TelaExtrato() {
        initComponents();
        limparCampos();
        btnBuscar.addActionListener(this::buscarExtrato);
        btnAplicar.addActionListener(this::aplicarRendimento);
        
        fBuscar.setColumns(15);
        fBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Número da Conta para Busca"));
        fBuscar.setToolTipText("Digite o número da conta (Ex: 12345-6)");
        
        setSize(700, 500);
        setLocationRelativeTo(null);
    }
    
    private void limparCampos() {
        lOpConta.setVisible(false);
        lResConta.setVisible(false);
        lOpContaR.setVisible(false);
        lResContaR.setVisible(false);
        lTitular.setText("");
        lNumConta.setText("");
        lTipoConta.setText("");
        lSaldo.setText("");
        btnAplicar.setVisible(false);
        ((DefaultTableModel) tTrans.getModel()).setRowCount(0);
    }
    
    private void atualizarInfoConta() {
        lTitular.setText(contaAtual.getTitular().getNome());
        lNumConta.setText(contaAtual.getNumeroConta());
        lTipoConta.setText(contaAtual instanceof ContaCorrente ? "Conta Corrente" : "Conta Poupança");
        lSaldo.setText(String.format("R$ %.2f", contaAtual.getSaldo()));
        btnAplicar.setVisible(contaAtual instanceof ContaPoupanca);
        
        // Atualizar Tabela
        DefaultTableModel model = (DefaultTableModel) tTrans.getModel();
        model.setRowCount(0);
        
        List<Transacao> transacoes = bancoService.buscarTransacoes(contaAtual.getNumeroConta());
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
        for (Transacao t : transacoes) {
            model.addRow(new Object[]{
                t.getDataHora().format(fmt),
                t.getTipoConta(),
                t.getDescricao() != null ? t.getDescricao() : "",
                String.format("R$ %.2f", t.getValor())
            });
        }
    }
    
    private void buscarExtrato(java.awt.event.ActionEvent evt) {
        String numero = fBuscar.getText().trim();
        contaAtual = bancoService.buscarContaPorNumero(numero);
        if (contaAtual != null) {
            limparCampos();
            atualizarInfoConta();
        } else {
            limparCampos();
            lOpConta.setText("Conta não encontrada.");
            lOpConta.setVisible(true);
        }
    }
    
    private void aplicarRendimento(java.awt.event.ActionEvent evt) {
        if (contaAtual instanceof ContaPoupanca) {
            if (bancoService.aplicarRendimento(contaAtual.getNumeroConta())) {
                buscarExtrato(null); // Recarrega
                lOpConta.setText("Rendimento aplicado com sucesso.");
                lOpConta.setVisible(true);
            } else {
                lOpConta.setText("Erro ao aplicar rendimento.");
                lOpConta.setVisible(true);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscar = new javax.swing.JButton();
        fBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lTitular = new javax.swing.JLabel();
        lNumConta = new javax.swing.JLabel();
        lTipoConta = new javax.swing.JLabel();
        lSaldo = new javax.swing.JLabel();
        lOpConta = new javax.swing.JLabel();
        lResConta = new javax.swing.JLabel();
        lResContaR = new javax.swing.JLabel();
        lOpContaR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tTrans = new javax.swing.JTable();
        btnAplicar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBuscar.setText("Buscar");

        jLabel1.setText("Titular:");

        jLabel2.setText("Número da conta:");

        jLabel3.setText("Tipo da conta:");

        jLabel4.setText("Saldo atual:");

        lOpConta.setText("jLabel9");

        lResConta.setText("jLabel10");

        lResContaR.setText("jLabel10");

        lOpContaR.setText("jLabel9");

        tTrans.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Data/Hora", "Tipo", "Descrição", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tTrans);

        btnAplicar.setText("Aplicar Rendimento");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(fBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lTitular)
                                    .addComponent(lNumConta)
                                    .addComponent(lTipoConta)
                                    .addComponent(lSaldo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lOpConta)
                                    .addComponent(lResConta))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lOpContaR)
                                    .addComponent(lResContaR))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAplicar)
                .addGap(170, 170, 170))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lOpContaR)
                        .addGap(18, 18, 18)
                        .addComponent(lResContaR))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnBuscar)
                            .addComponent(fBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(lNumConta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(lTipoConta))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(lSaldo)))
                            .addComponent(lTitular))
                        .addGap(18, 18, 18)
                        .addComponent(lOpConta)
                        .addGap(18, 18, 18)
                        .addComponent(lResConta)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAplicar)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaExtrato().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField fBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lNumConta;
    private javax.swing.JLabel lOpConta;
    private javax.swing.JLabel lOpContaR;
    private javax.swing.JLabel lResConta;
    private javax.swing.JLabel lResContaR;
    private javax.swing.JLabel lSaldo;
    private javax.swing.JLabel lTipoConta;
    private javax.swing.JLabel lTitular;
    private javax.swing.JTable tTrans;
    // End of variables declaration//GEN-END:variables
}
