/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

import banco.model.Cliente;
import banco.service.BancoService;
import java.util.List;

/**
 *
 * @author keslleyjr
 */
public class TelaCadastroContaPoupanca extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(TelaCadastroContaPoupanca.class.getName());

    private final BancoService bancoService = new BancoService();
    private List<Cliente> clientes;

    /**
     * Creates new form TelaCadastroContaPoupanca
     */
    public TelaCadastroContaPoupanca() {
        initComponents();
        carregarClientes();
        btnCad.addActionListener(this::cadastrarConta);
        btnCancel.addActionListener(e -> dispose());

        fSaldoInicial.setColumns(15);
        fRend.setColumns(15);
        fNumConta.setColumns(15);

        pack();
        setLocationRelativeTo(null);
    }

    private void carregarClientes() {
        clientes = bancoService.listarClientes();
        cBTitular.removeAllItems();
        for (Cliente cliente : clientes) {
            cBTitular.addItem(cliente.getNome() + " - " + cliente.getCpf());
        }
    }

    private void cadastrarConta(java.awt.event.ActionEvent evt) {
        int idx = cBTitular.getSelectedIndex();
        if (idx < 0) {
            setTitle("Erro: Selecione um titular.");
            return;
        }

        Cliente titular = clientes.get(idx);
        String numeroConta = fNumConta.getText().trim();
        String saldoTexto = fSaldoInicial.getText().replaceAll("[^0-9,]", "").replace(",", ".");
        String rendTexto = fRend.getText().replaceAll("[^0-9,]", "").replace(",", ".");

        if (numeroConta.isEmpty() || saldoTexto.isEmpty() || rendTexto.isEmpty()) {
            setTitle("Erro: Preencha todos os campos!");
            return;
        }

        try {
            double saldo = Double.parseDouble(saldoTexto);
            // Se rendTexto estiver em formato %, exemplo "0,5" ou "5"
            double taxaRendimento = Double.parseDouble(rendTexto) / 100.0;

            boolean sucesso = bancoService.cadastrarContaPoupanca(numeroConta, saldo, taxaRendimento, titular);
            if (sucesso) {
                dispose();
            } else {
                setTitle("Erro: Não foi possível cadastrar (Conta duplicada?).");
            }
        } catch (NumberFormatException e) {
            setTitle("Erro: Valores numéricos inválidos.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCad = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lTitular = new javax.swing.JLabel();
        cBTitular = new javax.swing.JComboBox<>();
        lNumConta = new javax.swing.JLabel();
        lSaldoInicial = new javax.swing.JLabel();
        lRend = new javax.swing.JLabel();
        fNumConta = new javax.swing.JTextField();
        fSaldoInicial = new javax.swing.JFormattedTextField();
        fRend = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCad.setText("Cadastrar");
        btnCad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnCancel.setText("Cancelar");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lTitular.setText("Titular:*");

        cBTitular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lNumConta.setText("Número da Conta:*");

        lSaldoInicial.setText("Saldo Inicial:*");

        lRend.setText("Taxa de Rendimento Mensal:*");

        fSaldoInicial.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        fRend.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(
                new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00%"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout
                                                .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout
                                                        .createSequentialGroup()
                                                        .addComponent(lNumConta)
                                                        .addPreferredGap(
                                                                javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(fNumConta, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                        jPanel1Layout.createSequentialGroup()
                                                                .addComponent(lTitular)
                                                                .addGap(84, 84, 84)
                                                                .addComponent(cBTitular,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lSaldoInicial)
                                                        .addComponent(lRend))
                                                .addGap(54, 54, 54)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fRend, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fSaldoInicial,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(199, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lTitular)
                                        .addComponent(cBTitular, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lNumConta)
                                        .addComponent(fNumConta, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lSaldoInicial)
                                        .addComponent(fSaldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lRend)
                                        .addComponent(fRend, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(42, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnCad)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnCancel)
                                                .addGap(92, 92, 92)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37,
                                        Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnCad)
                                        .addComponent(btnCancel))
                                .addGap(28, 28, 28)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaCadastroContaPoupanca().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCad;
    private javax.swing.JButton btnCancel;
    private javax.swing.JComboBox<String> cBTitular;
    private javax.swing.JTextField fNumConta;
    private javax.swing.JFormattedTextField fRend;
    private javax.swing.JFormattedTextField fSaldoInicial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lNumConta;
    private javax.swing.JLabel lRend;
    private javax.swing.JLabel lSaldoInicial;
    private javax.swing.JLabel lTitular;
    // End of variables declaration//GEN-END:variables
}
