/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package banco.ui;

import banco.model.Usuario;
import banco.service.UsuarioService;
import java.awt.event.ActionEvent;
import java.util.logging.Level;
import javax.swing.Timer;

/**
 *
 * @author keslleyjr
 */
public class TelaLogin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());
    private static final int MAX_TENTATIVAS_INVALIDAS = 3;
    private static final int SEGUNDOS_BLOQUEIO = 30;

    private final UsuarioService usuarioService = new UsuarioService();
    private int tentativasInvalidas = 0;
    private int segundosRestantes = SEGUNDOS_BLOQUEIO;
    private Timer bloqueioTimer;

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        inicializarEstadoLogin();
    }

    private void inicializarEstadoLogin() {
        lErro.setVisible(false);
        timer.setVisible(false);
        timer.setText(String.valueOf(SEGUNDOS_BLOQUEIO));
    }

    private void mostrarErro(String mensagem) {
        lErro.setText(mensagem);
        lErro.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lLogin = new javax.swing.JLabel();
        lSenha = new javax.swing.JLabel();
        fLogin = new javax.swing.JTextField();
        fSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        lErro = new javax.swing.JLabel();
        timer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lLogin.setText("Login:");

        lSenha.setText("Senha:");

        fSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        btnEntrar.setText("Entrar");
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        lErro.setForeground(new java.awt.Color(255, 0, 0));
        lErro.setText("Credenciais Inválidas");

        timer.setText("30");

        jLabel1.setText("Entrada no Sistema");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lLogin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lSenha)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timer)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(fSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(7, 7, 7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEntrar)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(fLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lErro)))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLogin)
                    .addComponent(fLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lSenha)
                    .addComponent(fSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(timer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lErro)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if (!btnEntrar.isEnabled()) {
            return;
        }

        String login = fLogin.getText();
        char[] senha = fSenha.getPassword();
        boolean autenticado;

        Usuario usuarioLogado = null;
        try {
            usuarioLogado = usuarioService.autenticar(login, senha);
            autenticado = usuarioLogado != null;
        } catch (RuntimeException exception) {
            logger.log(Level.SEVERE, "Erro ao autenticar usuário", exception);
            mostrarErro(exception.getMessage());
            return;
        }

        if (autenticado) {
            tentativasInvalidas = 0;
            if (bloqueioTimer != null && bloqueioTimer.isRunning()) {
                bloqueioTimer.stop();
            }
            lErro.setVisible(false);
            timer.setVisible(false);
            new TelaMenuPrincipal(usuarioLogado).setVisible(true);
            dispose();
            return;
        }

        tentativasInvalidas++;
        if (tentativasInvalidas >= 1) {
            mostrarErro("Credenciais Inválidas");
        }

        if (tentativasInvalidas >= MAX_TENTATIVAS_INVALIDAS) {
            bloquearAcesso();
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void bloquearAcesso() {
        btnEntrar.setEnabled(false);
        timer.setVisible(true);
        segundosRestantes = SEGUNDOS_BLOQUEIO;
        timer.setText(String.valueOf(segundosRestantes));

        bloqueioTimer = new Timer(1000, (ActionEvent event) -> {
            segundosRestantes--;
            timer.setText(String.valueOf(segundosRestantes));
            if (segundosRestantes <= 0) {
                bloqueioTimer.stop();
                btnEntrar.setEnabled(true);
                timer.setVisible(false);
                tentativasInvalidas = 0;
                timer.setText(String.valueOf(SEGUNDOS_BLOQUEIO));
            }
        });
        bloqueioTimer.start();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JTextField fLogin;
    private javax.swing.JPasswordField fSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lErro;
    private javax.swing.JLabel lLogin;
    private javax.swing.JLabel lSenha;
    private javax.swing.JLabel timer;
    // End of variables declaration//GEN-END:variables
}
